# Generated by Django 4.2.2 on 2023-06-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
