# Generated by Django 4.2.2 on 2023-06-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_app', '0002_alter_item_quantity_alter_store_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='measure',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('LB', 'Pound'), ('OZ', 'Ounce'), ('GMS', 'Gram')], max_length=3, null=True),
        ),
    ]
