# Generated by Django 4.2.2 on 2023-07-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_app', '0003_item_measure'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=64)),
                ('store_location', models.CharField(max_length=256)),
                ('store_zipcode', models.IntegerField()),
                ('store_item_name', models.CharField(max_length=64)),
                ('store_item_category', models.CharField(max_length=64)),
                ('store_item_brand', models.CharField(max_length=64)),
                ('store_item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('store_item_quantity', models.IntegerField()),
                ('store_item_measure', models.CharField(choices=[('KG', 'Kilogram'), ('LB', 'Pound'), ('OZ', 'Ounce'), ('GMS', 'Gram'), ('EA', 'Each')], max_length=3, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='measure',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('LB', 'Pound'), ('OZ', 'Ounce'), ('GMS', 'Gram'), ('EA', 'Each')], max_length=3, null=True),
        ),
    ]
