# Generated by Django 4.2.2 on 2023-07-24 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_app', '0004_storeitem_alter_item_measure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeitem',
            old_name='store_item_brand',
            new_name='item_brand',
        ),
        migrations.RenameField(
            model_name='storeitem',
            old_name='store_item_category',
            new_name='item_category',
        ),
        migrations.RenameField(
            model_name='storeitem',
            old_name='store_item_measure',
            new_name='item_measure',
        ),
        migrations.RenameField(
            model_name='storeitem',
            old_name='store_item_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='storeitem',
            old_name='store_item_price',
            new_name='item_price',
        ),
        migrations.RenameField(
            model_name='storeitem',
            old_name='store_item_quantity',
            new_name='item_quantity',
        ),
    ]
