# Generated by Django 4.2.4 on 2023-08-04 02:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('price_app', '0005_rename_store_item_brand_storeitem_item_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='added_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
